# Generated by Django 4.0.5 on 2022-06-02 18:32
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cron_time", models.CharField(max_length=255, verbose_name="Cron")),
                ("exact_time", models.DateTimeField(blank=True, null=True, verbose_name="Exact time")),
                ("code", models.TextField(blank=True, null=True, verbose_name="Code")),
                ("last_execution_date", models.DateTimeField(blank=True, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("user_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="user_profile.userprofile")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
