# Generated by Django 4.0.5 on 2022-06-02 18:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
