# Generated by Django 4.0.5 on 2022-06-03 11:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0002_snippet_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Cron"),
        ),
        migrations.AddField(
            model_name="snippet",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Cron"),
        ),
    ]
